WI-1888-prices-real-time-webhook
woowup/vtex-woowup-connector pull request #166
Opened 2023-12-01 15:12 UTC by evillafane

2023-12-01 15:55 UTC, joaquin-lonardi requested changes

2023-12-01 15:55 UTC, joaquin-lonardi commented on src/Stages/Products/VTEXWoowUpProductMapper.php
> +    protected function skipEmptyPrices($product)
El nombre skipEmptyPrices me hace pensar que la función valida si hay un flag activo que hace que si un precio está vacío lo omita. Pero en realidad lo omite siempre que se de esa situación. Yo le cambiaría el nombre por isPricesEmpty o similar.

2023-12-01 15:55 UTC, joaquin-lonardi commented on src/Stages/Products/VTEXWoowUpProductWorkerMapper.php
> +        // $prices = $this->setPrice($product, $vtexProduct);
Están ok estos comentarios?

2023-12-01 15:55 UTC, joaquin-lonardi commented on src/Stages/Products/VTEXWoowUpProductWorkerMapper.php
> +//
No habría que borrar esto directamente?

2023-12-01 15:55 UTC, joaquin-lonardi commented on src/Stages/Products/VTEXWoowUpProductWorkerMapper.php
>          if (!$this->hasStockOrPrice($stock, $prices)) {
Este $prices no parece estar definido

2023-12-01 15:55 UTC, joaquin-lonardi commented on src/Stages/Products/VTEXWoowUpProductWithoutChildrenMapper.php
> +            $this->vtexConnector->_logger->info("Skipping product with empty prices: $sku");
$sku no está definido acá pareciera

2023-12-18 19:20 UTC, evillafane reviewed
@joaquin-lonardi listo

2023-12-18 19:29 UTC, joaquin-lonardi approved these changes

2024-01-02 13:03 UTC, merged